FROM mhart/alpine-node:8.11

RUN apk add --no-cache bash git zip curl make

# install AWS_CLI (via python)
RUN apk -Uuv add groff less python py-pip && \
pip install awscli && \
apk --purge -v del py-pip && \
rm /var/cache/apk/*

WORKDIR /src

ENV PATH=$PATH:/src/node_modules/.bin
