service: damo

frameworkVersion: "=1.26.*"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  memorySize: 128

custom:
  stageVariables:
    env: ${self:provider.stage}
  dev:

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  main:
    handler: bin/main
    integration: lambda-proxy
    events:
      - http: 
          method: ANY 
          path: /{proxy+}
    environment:
      ALLOW_ORIGIN: ${env:ALLOW_ORIGIN}